import React, { createContext, useContext, useState } from 'react';
import { SupportedLanguage } from '../types';

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  languageLabel: string;
  t: (key: string, fallback?: string) => string;
  tcrop: (cropName: string) => string;
  tcity: (cityName: string) => string;
  tgrade: (grade: string) => string;
  tstatus: (status: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const CROP_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  Cotton: { en: 'Cotton (Kapas)', hi: 'कपास (कॉटन)', mr: 'कापूस' },
  Soybean: { en: 'Soybean', hi: 'सोयाबीन', mr: 'सोयाबीन' },
  Wheat: { en: 'Wheat', hi: 'गेहूं', mr: 'गहू' },
  Tomato: { en: 'Tomato', hi: 'टमाटर', mr: 'टोमॅटो' },
  Onion: { en: 'Onion', hi: 'प्याज', mr: 'कांदा' },
  Grapes: { en: 'Grapes', hi: 'अंगूर', mr: 'द्राक्षे' },
  Banana: { en: 'Banana', hi: 'केला', mr: 'केळी' },
  Chickpea: { en: 'Chickpea (Gram)', hi: 'चना (दाल)', mr: 'हरभरा (चना)' },
  Orange: { en: 'Nagpur Orange', hi: 'नागपुर संतरा', mr: 'नागपूर संत्री' },
  Sugarcane: { en: 'Sugarcane', hi: 'गन्ना', mr: 'ऊस' },
  Maize: { en: 'Maize (Corn)', hi: 'मक्का', mr: 'मका' },
};

const CITY_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  Amravati: { en: 'Amravati', hi: 'अमरावती', mr: 'अमरावती' },
  Nagpur: { en: 'Nagpur', hi: 'नागपुर', mr: 'नागपूर' },
  Akola: { en: 'Akola', hi: 'अकोला', mr: 'अकोला' },
  Wardha: { en: 'Wardha', hi: 'वर्धा', mr: 'वर्धा' },
  Nashik: { en: 'Nashik', hi: 'नासिक', mr: 'नाशिक' },
  Pune: { en: 'Pune', hi: 'पुणे', mr: 'पुणे' },
  Mumbai: { en: 'Mumbai', hi: 'मुंबई', mr: 'मुंबई' },
  Jalgaon: { en: 'Jalgaon', hi: 'जलगांव', mr: 'जळगाव' },
  Kolhapur: { en: 'Kolhapur', hi: 'कोल्हापुर', mr: 'कोल्हापूर' },
  Sangli: { en: 'Sangli', hi: 'सांगली', mr: 'सांगली' },
  Solapur: { en: 'Solapur', hi: 'सोलापुर', mr: 'सोलापूर' },
  Ahmednagar: { en: 'Ahmednagar', hi: 'अहमदनगर', mr: 'अहिल्यानगर (अहमदनगर)' },
  Dindori: { en: 'Dindori', hi: 'दिंडोरी', mr: 'दिंडोरी' },
  Niphad: { en: 'Niphad', hi: 'निफाड', mr: 'निफाड' },
  Baramati: { en: 'Baramati', hi: 'बारामती', mr: 'बारामती' },
};

const GRADE_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  GRADE_A: { en: 'Grade A (Premium Export Quality)', hi: 'श्रेणी "ए" (उत्कृष्ट प्रीमियम गुणवत्ता)', mr: 'प्रत "अ" (उत्कृष्ट निर्यात दर्जा)' },
  GRADE_B: { en: 'Grade B (Standard Market Quality)', hi: 'श्रेणी "बी" (मानक मंडी गुणवत्ता)', mr: 'प्रत "ब" (मानक बाजार दर्जा)' },
  GRADE_C: { en: 'Grade C (Fair Processing Quality)', hi: 'श्रेणी "सी" (औसत प्रोसेसिंग गुणवत्ता)', mr: 'प्रत "क" (प्रक्रिया दर्जा)' },
};

const STATUS_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  AVAILABLE: { en: 'Available for Sale', hi: 'बिक्री के लिए उपलब्ध', mr: 'विक्रीसाठी उपलब्ध' },
  IN_TRANSIT: { en: 'In Transit', hi: 'परिवहन में (मार्ग पर)', mr: 'थेट वाहतुकीत (मार्गावर)' },
  DELIVERED: { en: 'Delivered', hi: 'पहुंच गया', mr: 'वितरित (पोहोचले)' },
  COMPLETED: { en: 'Completed & Settled', hi: 'पूर्ण व भुगतान संपन्न', mr: 'पूर्ण व चुकता झाले' },
  PENDING: { en: 'Pending Review', hi: 'समीक्षा लंबित', mr: 'प्रलंबित' },
  ACCEPTED: { en: 'Accepted', hi: 'स्वीकृत', mr: 'स्वीकृत' },
  COUNTERED: { en: 'Countered', hi: 'काउंटर ऑफर भेजा', mr: 'प्रति-प्रस्ताव पाठवला' },
  PLANNED: { en: 'Planned for Season', hi: 'मौसम हेतु नियोजित', mr: 'हंगामासाठी नियोजित' },
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Navigation & App Shell
    dashboard: 'Dashboard',
    aiAdvisor: 'AI Advisor (Saarthi)',
    myCrops: 'My Crops',
    marketIntel: 'Market Intelligence',
    findBestMarket: 'Find Best Market',
    findBuyers: 'Find Buyers',
    offersNegotiations: 'Offers & Negotiations',
    cropPlanning: 'Smart Crop Recommendation',
    qualityAssessment: 'AI Quality Assessment',
    orders: 'Orders',
    logistics: 'Logistics & Transit',
    earnings: 'Earnings Analytics',
    cropPassport: 'Digital Crop Passport',
    fairPriceEngine: 'Fair Price Engine',
    searchPlaceholder: 'Search crops, mandis, buyers, orders...',
    signOut: 'Sign Out',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    notifications: 'Notifications',
    allCaughtUp: 'You are all caught up!',

    // Dashboard Greetings & Cards
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    docaTagline: 'Government of India — Department of Consumer Affairs (DoCA)',
    heroSub: 'Direct Agri-Commerce Engine connecting farmers, buyers, and FPOs with AI quality grading and fair price protection.',
    farmHolding: 'Farm holding',
    acres: 'Acres',
    inLocation: 'in',
    trustScore: 'Trust Score',
    produceQualityScanner: 'Produce Quality Scanner',
    scanProduceDesc: 'Instant multi-photo optical inspection with live APMC valuation.',
    scanProduceBtn: 'Run Scan',
    cropRecommendationTitle: 'Crop Recommendation',
    cropRecommendationDesc: 'Area-based scientific matching: soil, climate, and profit forecasting.',
    planCropsBtn: 'Plan Crops',
    findBuyersTitle: 'Find Verified Buyers',
    findBuyersDesc: 'Direct reverse-bidding and bulk corporate procurement.',
    viewBuyersBtn: 'View Buyers',
    fairPriceNegotiation: 'Fair Price Negotiation',
    fairPriceNegotiationDesc: 'AI benchmark protection against predatory lowball offers.',
    viewOffersBtn: 'View Offers',
    registeredCropsTitle: 'My Registered Crops',
    registeredCropsSub: 'Batches harvested and ready for direct commerce.',
    addNewBatch: 'Add New Crop Batch',
    viewPassport: 'Digital Passport',
    activeOrdersCard: 'Active Direct Orders',
    totalEarningsCard: 'Total Verified Earnings',
    offersReceivedCard: 'Active Buyer Offers',
    liveMandiSpotPrices: 'Live APMC Mandi Spot Prices',
    modalPriceLabel: 'Modal Mandi Rate',
    change24h: '24h Trend',
    viewMandiDetails: 'View Mandi Analytics',

    // Decision Engine Cockpit
    decisionEngineHeader: 'One-Screen Decision Engine Cockpit',
    decisionEngineSub: 'Live synthesis: your crop, AI price forecast, best nearby market, and direct buyer match.',
    harvestDetailsTitle: 'Harvest Lot Details',
    cropLabel: 'Crop',
    quantityLabel: 'Quantity',
    qualityGradeLabel: 'Quality Grade',
    shelfLifeLabel: 'Shelf Life',
    marketIntelligenceTitle: 'Market Intelligence',
    currentMandiRate: 'Current Mandi Rate',
    predictedRate3Days: 'Predicted Rate (3 Days)',
    fairPriceRangeLabel: 'Fair Price Range',
    aiRecommendationLabel: 'AI Recommendation',
    bestMarketTitle: 'Recommended Best Market',
    grossMarketPrice: 'Gross Market Price',
    transportFreight: 'Transport / Freight',
    platformTechFee: 'Platform Tech Fee',
    netRealizationRate: 'Net Realization Rate',
    estimatedBatchNet: 'Est. Net Batch Realization',
    bestMatchedBuyerTitle: 'Best Matched Bulk Buyer',
    buyerNameLabel: 'Buyer Entity',
    matchScoreLabel: 'Match Score',
    buyerOfferRate: 'Offered Price',
    requiredDelivery: 'Required Delivery',
    acceptBuyerOfferBtn: 'Accept Offer & Initiate Escrow',
    smartLogisticsTitle: 'Smart Direct Logistics',
    logisticsSavings: 'Consolidated Freight Savings',
    pooledTruckRoute: 'Direct Farm-to-Buyer Corridor',

    // Crop Planning
    cropRecTitle: 'Smart Crop Recommendation & Suitability Engine',
    cropRecSubtitle: 'Deterministic agronomic scoring, soil matching, and ICAR & OWID yield benchmarks for your specific land.',
    analyzeMyLand: 'Analyze My Land',
    analyzingLand: 'Analyzing Soil, Climate & Market...',
    topRecommendedCrops: 'Top Recommended Crops for Your Farm',
    overallSuitabilityScore: 'Overall Suitability Score',
    whyThisCrop: 'Why this crop for your land?',
    financialEstimates: 'Financial Projections (Your Farm Size)',
    cultivationCost: 'Est. Cultivation Cost',
    projectedGrossRevenue: 'Projected Revenue',
    projectedNetProfit: 'Projected Net Profit',
    yieldBenchmarking: 'Yield Gap Benchmarking (OWID & ICAR)',
    districtAverage: 'District Historical Yield',
    stateAverage: 'State Average',
    nationalBenchmark: 'National Progressive Benchmark',
    yieldGap: 'Yield Gap',
    askSaarthi: 'Ask Saarthi About This Crop',
    nearbyAgriCenters: 'Nearby KVKs & Soil Testing Labs',
    planThisCrop: 'Plan This Crop',
    activePlansTitle: 'My Active Crop Cultivation Plans',

    // Quality Assessment
    qualityAssessmentTitle: 'Produce Quality Scanner & Market Value Engine',
    qualityAssessmentSubtitle: 'Real-time computer vision grading directly connected to APMC mandi arrivals, MSP benchmarks, and quality pricing rules.',
    cameraAndProduceInput: 'Camera & Produce Input',
    liveSensor: 'Live Sensor',
    uploadPhotosTab: 'Upload Photos',
    selectRegisteredCropBatch: 'Select Registered Crop Batch',
    produceCommodity: 'Produce Commodity',
    batchQuantityKg: 'Batch Quantity (kg)',
    runAiQualityEngine: 'Run AI Quality & Market Valuation Engine',
    clickToUploadPhoto: 'Click to upload harvest photograph',
    multiPhotoInspectionTray: 'Multi-Photo Inspection Tray',
    opticalScore: 'Optical Score',
    ripenessIndex: 'Ripeness Index',
    visibleDefects: 'Visible Defects',
    threeStateVerification: '3-State Optical Verification',
    detected: 'DETECTED',
    notDetected: 'NOT DETECTED',
    notAssessable: 'NOT ASSESSABLE',
    estimatedQualityPrice: 'Estimated Quality Price',
    totalBatchValue: 'Total Batch Value',
    mandiModalBaseline: 'Mandi Modal Baseline',
    premiumOverModal: 'Premium over Modal',
    discountUnderModal: 'Quality Discount',
    changePhoto: 'Change Photo',
    clearAll: 'Clear All',
    capturePhotosTitle: 'Step 1: Multi-Photo Optical Capture',
    startLiveCamera: 'Start Live Camera',
    stopLiveCamera: 'Stop Camera',
    takeSnapshot: 'Capture Photo',
    orUploadImages: 'Or Upload High-Resolution Photos',
    imageQualityPreCheck: 'Image Quality Pre-Check Audit',
    structuredObservationsTitle: 'Structured Visual Observations',
    estimatedMarketValueTitle: 'Estimated Market Value Realization',
    expectedMandiRange: 'Expected Mandi Range',
    batchValueRealization: 'Batch Value Realization',
    potentialFarmerGain: 'Potential Farmer Gain over Baseline',
    priceComparisonByGrade: 'Price Comparison by Quality Grade',
    attachInspectionBtn: 'Attach Inspection & Value to Crop Batch',
    backToMyCrops: 'Back to My Crops',
    qualityGrade: 'Quality Grade',
    targetFocus: 'TARGET FOCUS',
    opticalSensorActive: 'OPTICAL SENSOR ACTIVE',
    liveCameraInactive: 'Live Camera Inactive',
    launchCameraSensor: 'Launch Camera Sensor',
    noAssessmentRunYet: 'No Assessment Run Yet',
    noAssessmentRunDesc: 'Point your device camera at your harvest batch or upload photos. The engine will inspect quality features and compute live market valuation.',
    processingScanner: 'Processing Quality Scanner & Pricing Engine...',
    howWasPriceCalculated: 'How was this price calculated? (Transparency Audit)',
    currentBatchGrade: 'Current Batch Grade',
    disclaimer: 'Disclaimer',
    inspectionAttachedSuccess: 'Quality Inspection Attached to Batch in Database!',
    viewInMyCrops: 'View in My Crops',
    manageListings: 'Manage Listings',

    // Negotiation & Offers
    offersTitle: 'Offers & Fair Price Negotiations',
    offersSubtitle: 'Direct negotiation threads with buyers, backed by objective market benchmarks.',
    receivedOffers: 'Received Offers',
    sentOffers: 'Sent Offers',
    offeredPrice: 'Offered Price',
    fairFloorPrice: 'Fair Floor Price',
    counterOfferBtn: 'Submit Counter-Offer',
    acceptOfferBtn: 'Accept Deal',
    rejectOfferBtn: 'Decline Offer',
    predatoryAlertTitle: 'Predatory Pricing Warning',
    predatoryAlertDesc: 'This offer is significantly below the fair market floor. We recommend countering.',

    // Orders & Logistics
    ordersTitle: 'Orders & Contract Lifecycles',
    ordersSubtitle: 'Secure milestone-backed sales contracts with automated escrow guarantees.',
    orderCode: 'Order Code',
    escrowStatus: 'Escrow Status',
    logisticsTrackingTitle: 'Live Logistics & Freight Transit',
    transitStage: 'Transit Stage',
    driverContact: 'Driver Contact',
    vehicleNumber: 'Vehicle Number',

    // Buyer Matching & Direct Commerce
    buyerMatchingTitle: 'AI Buyer Matching Engine',
    buyerMatchingSub: '6-factor weighted algorithm: Price, Proximity, Quality Grade, Demand Urgency, and Escrow Reliability.',
    filterByCrop: 'Filter by Crop',
    filterByLocation: 'Filter by Location',
    allCrops: 'All Crops',
    allLocations: 'All Locations',
    budgetRate: 'Budget Rate',
    targetVolume: 'Target Volume',
    deliveryDate: 'Delivery Date',
    sendOfferBtn: 'Send Offer',
    sendOfferModalTitle: 'Send Trade Offer',
    sendOfferModalDesc: 'Submit your proposed price and quantity. The Fair Price Engine will assist in negotiating the best deal.',
    buyerTargetBudget: 'Buyer Target Budget',
    fairPriceCorridor: 'Fair Price Corridor',
    escrowSecurity: 'Escrow Security',
    guaranteed100: '100% Guaranteed',
    yourPricePerKg: 'Your Price (₹/kg)',
    quantityKgLabel: 'Quantity (kg)',
    dispatchNotes: 'Dispatch & Quality Notes',
    sendFormalOffer: 'Send Formal Offer',
    viewDetails: 'View Details',
    netRealizationEngine: 'Net Realization Engine',
    bestMarketHeading: 'Best Market & Mandi Recommendation',
    bestMarketSub: 'Compare nearby and regional APMC mandis after factoring in transport, loading, and mandi cess.',
    originDistrict: 'Origin Farm District',
    selectCrop: 'Select Crop',
    harvestQuantityKg: 'Harvest Quantity (kg)',
    calculateNetRealization: 'Calculate Net Realization',
    recommendedMandi: 'Top Recommended Mandi',
    alternativeMarkets: 'Alternative APMC Mandis',
    proximityNet: 'Proximity Net',
    aiFairPriceVerified: 'AI Fair Price Verified',
    docaEscrowProtected: 'DoCA Escrow Protected',
    truckFillRate: 'Truck Fill Rate',
    standardFreight: 'Standard Freight',
    savedAmount: 'Saved',
    distance: 'Distance',
    escrowSecured: '100% Escrow Secured',
    verifiedCorporateBuyer: 'Verified Direct Corporate Buyer',
    calculatedAfterFreight: 'Calculated after freight',
    netRealizationSubtitle: 'Net farm-gate realization',
    activeOrderSubtitle: 'In transit to buyer hub',
    viewNegotiations: 'View Active Negotiations',
    noBuyersFound: 'No active buyer requirements found for this crop and location.',
  },

  hi: {
    // Navigation & App Shell
    dashboard: 'डैशबोर्ड',
    aiAdvisor: 'एआई सलाहकार (सारथी)',
    myCrops: 'मेरी फसलें',
    marketIntel: 'बाजार भाव और मांग',
    findBestMarket: 'सर्वश्रेष्ठ मंडी खोजें',
    findBuyers: 'सत्यापित खरीदार',
    offersNegotiations: 'प्रस्ताव और बातचीत',
    cropPlanning: 'स्मार्ट फसल अनुशंसा',
    qualityAssessment: 'एआई गुणवत्ता जांच',
    orders: 'सक्रिय ऑर्डर',
    logistics: 'सीधा परिवहन (लॉजिस्टिक्स)',
    earnings: 'आय और बचत विश्लेषण',
    cropPassport: 'डिजिटल क्रॉप पासपोर्ट',
    fairPriceEngine: 'उचित मूल्य इंजन',
    searchPlaceholder: 'फसलें, मंडियां, खरीदार खोजें...',
    signOut: 'साइन आउट करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveChanges: 'बदलाव सहेजें',
    cancel: 'रद्द करें',
    notifications: 'सूचनाएं (नोटिफिकेशन)',
    allCaughtUp: 'कोई नई सूचना नहीं है!',

    // Dashboard Greetings & Cards
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    docaTagline: 'भारत सरकार — उपभोक्ता मामले विभाग (DoCA)',
    heroSub: 'एआई गुणवत्ता ग्रेडिंग और उचित मूल्य सुरक्षा के साथ किसानों, खरीदारों और एफपीओ को जोड़ने वाला प्रत्यक्ष कृषि-वाणिज्य इंजन।',
    farmHolding: 'खेत का रकबा',
    acres: 'एकड़',
    inLocation: 'स्थान',
    trustScore: 'विश्वास स्कोर',
    produceQualityScanner: 'फसल गुणवत्ता स्कैनर',
    scanProduceDesc: 'लाइव एपीएमसी मंडी दरों के साथ त्वरित ऑप्टिकल गुणवत्ता मूल्यांकन।',
    scanProduceBtn: 'स्कैन शुरू करें',
    cropRecommendationTitle: 'स्मार्ट फसल अनुशंसा',
    cropRecommendationDesc: 'मिट्टी, जलवायु और बाजार मांग के आधार पर वैज्ञानिक फसल चयन।',
    planCropsBtn: 'फसल योजना बनाएं',
    findBuyersTitle: 'सत्यापित खरीदार खोजें',
    findBuyersDesc: 'दलालों के बिना सीधे थोक खरीदारों और मिल मालिकों से जुड़ें।',
    viewBuyersBtn: 'खरीदार देखें',
    fairPriceNegotiation: 'उचित मूल्य बातचीत',
    fairPriceNegotiationDesc: 'कम दाम वाले अनुचित ऑफर्स के खिलाफ एआई सुरक्षा।',
    viewOffersBtn: 'ऑफर देखें',
    registeredCropsTitle: 'मेरी पंजीकृत फसलें (फसल लॉट)',
    registeredCropsSub: 'कटाई उपरांत सीधी बिक्री हेतु तैयार प्रमाणित फसल लॉट।',
    addNewBatch: 'नया फसल लॉट जोड़ें',
    viewPassport: 'डिजिटल पासपोर्ट',
    activeOrdersCard: 'सक्रिय सीधे ऑर्डर',
    totalEarningsCard: 'कुल प्रमाणित आय',
    offersReceivedCard: 'प्राप्त खरीद ऑफर',
    liveMandiSpotPrices: 'लाइव एपीएमसी मंडी भाव',
    modalPriceLabel: 'औसत मंडी दर (मॉडल रेट)',
    change24h: '२४ घंटे का रुझान',
    viewMandiDetails: 'मंडी विश्लेषण देखें',

    // Decision Engine Cockpit
    decisionEngineHeader: 'एक-स्क्रीन निर्णय इंजन कॉकपिट',
    decisionEngineSub: 'आपकी फसल, मूल्य पूर्वानुमान, सर्वोत्तम नजदीकी मंडी और खरीदार का सीधा समन्वय।',
    harvestDetailsTitle: 'फसल लॉट विवरण',
    cropLabel: 'फसल',
    quantityLabel: 'मात्रा',
    qualityGradeLabel: 'गुणवत्ता श्रेणी',
    shelfLifeLabel: 'सुरक्षित भंडारण अवधि',
    marketIntelligenceTitle: 'बाजार खुफिया जानकारी',
    currentMandiRate: 'वर्तमान मंडी भाव',
    predictedRate3Days: '३ दिन बाद अनुमानित भाव',
    fairPriceRangeLabel: 'उचित मूल्य दायरा',
    aiRecommendationLabel: 'एआई परामर्श',
    bestMarketTitle: 'सर्वोत्तम अनुशंसित मंडी',
    grossMarketPrice: 'सकल मंडी मूल्य',
    transportFreight: 'माल ढुलाई / परिवहन खर्च',
    platformTechFee: 'प्लेटफॉर्म शुल्क',
    netRealizationRate: 'शुद्ध प्राप्ति दर',
    estimatedBatchNet: 'कुल शुद्ध प्राप्ति (लॉट मूल्य)',
    bestMatchedBuyerTitle: 'सर्वोत्तम मेल खाने वाला खरीदार',
    buyerNameLabel: 'खरीदार कंपनी',
    matchScoreLabel: 'मैच स्कोर',
    buyerOfferRate: 'प्रस्तावित दर',
    requiredDelivery: 'डिलीवरी समय',
    acceptBuyerOfferBtn: 'ऑफर स्वीकार करें व एस्क्रो शुरू करें',
    smartLogisticsTitle: 'स्मार्ट सीधा परिवहन',
    logisticsSavings: 'साझा ढुलाई में बचत',
    pooledTruckRoute: 'सीधा खेत-से-खरीदार गलियारा',

    // Crop Planning
    cropRecTitle: 'स्मार्ट फसल अनुशंसा एवं भूमि उपयुक्तता इंजन',
    cropRecSubtitle: 'आपकी भूमि के लिए ICAR एवं OWID डेटा पर आधारित सटीक वैज्ञानिक गणना एवं लाभ पूर्वानुमान।',
    analyzeMyLand: 'मेरी भूमि का विश्लेषण करें',
    analyzingLand: 'मिट्टी, मौसम और बाजार का विश्लेषण हो रहा है...',
    topRecommendedCrops: 'आपकी भूमि के लिए शीर्ष अनुशंसित ३ फसलें',
    overallSuitabilityScore: 'समग्र उपयुक्तता स्कोर',
    whyThisCrop: 'आपकी जमीन के लिए यह फसल क्यों?',
    financialEstimates: 'वित्तीय अनुमान (आपके खेत का रकबा)',
    cultivationCost: 'अनुमानित लागत',
    projectedGrossRevenue: 'अनुमानित सकल आय',
    projectedNetProfit: 'अनुमानित शुद्ध लाभ',
    yieldBenchmarking: 'उत्पादकता तुलना (OWID एवं ICAR)',
    districtAverage: 'जिले की ऐतिहासिक उपज',
    stateAverage: 'राज्य का औसत',
    nationalBenchmark: 'राष्ट्रीय प्रगतिशील मानक',
    yieldGap: 'उत्पादकता अंतर (गैप)',
    askSaarthi: 'सारथी से इस फसल के बारे में पूछें',
    nearbyAgriCenters: 'नजदीकी केवीके और मिट्टी परीक्षण प्रयोगशालाएं',
    planThisCrop: 'यह फसल चुनें और प्लान बनाएं',
    activePlansTitle: 'मेरी सक्रिय फसल योजनाएं',

    // Quality Assessment
    qualityAssessmentTitle: 'फसल गुणवत्ता स्कैनर एवं बाजार मूल्य निर्धारण इंजन',
    qualityAssessmentSubtitle: 'एपीएमसी मंडी आवक, एमएसपी और गुणवत्ता मूल्य नियमों से सीधे जुड़ा रीयल-टाइम कंप्यूटर विज़न ग्रेडिंग इंजन।',
    cameraAndProduceInput: 'कैमरा व फसल इनपुट',
    liveSensor: 'लाइव सेंसर',
    uploadPhotosTab: 'फोटो अपलोड करें',
    selectRegisteredCropBatch: 'पंजीकृत फसल बैच चुनें',
    produceCommodity: 'फसल / उत्पाद',
    batchQuantityKg: 'बैच मात्रा (किलो)',
    runAiQualityEngine: 'एआई गुणवत्ता व बाजार मूल्य जांच शुरू करें',
    clickToUploadPhoto: 'फसल की फोटो अपलोड करने के लिए क्लिक करें',
    multiPhotoInspectionTray: 'बहु-फोटो निरीक्षण ट्रे',
    opticalScore: 'ऑप्टिकल स्कोर',
    ripenessIndex: 'परिपक्वता सूचकांक',
    visibleDefects: 'दृश्य दोष / क्षति',
    threeStateVerification: '३-स्तरीय ऑप्टिकल सत्यापन',
    detected: 'पाया गया',
    notDetected: 'नहीं मिला',
    notAssessable: 'आंकलन योग्य नहीं',
    estimatedQualityPrice: 'अनुमानित गुणवत्ता भाव',
    totalBatchValue: 'कुल लॉट मूल्य',
    mandiModalBaseline: 'मंडी मोडल आधार भाव',
    premiumOverModal: 'मोडल से प्रीमियम (अतिरिक्त)',
    discountUnderModal: 'गुणवत्ता कटौती (छूट)',
    changePhoto: 'फोटो बदलें',
    clearAll: 'सभी हटाएं',
    capturePhotosTitle: 'चरण १: बहु-फोटो ऑप्टिकल कैप्चर',
    startLiveCamera: 'लाइव कैमरा चालू करें',
    stopLiveCamera: 'कैमरा बंद करें',
    takeSnapshot: 'फोटो खींचें',
    orUploadImages: 'या उच्च गुणवत्ता वाली फोटो अपलोड करें',
    imageQualityPreCheck: 'फोटो गुणवत्ता पूर्व-जांच',
    structuredObservationsTitle: 'संरचित दृश्य निरीक्षण (३-स्तरीय मॉडल)',
    estimatedMarketValueTitle: 'अनुमानित बाजार मूल्य प्राप्ति',
    expectedMandiRange: 'अपेक्षित मंडी भाव दायरा',
    batchValueRealization: 'कुल लॉट मूल्य प्राप्ति',
    potentialFarmerGain: 'औसत मंडी से किसान को अतिरिक्त लाभ',
    priceComparisonByGrade: 'गुणवत्ता श्रेणी अनुसार मूल्य तुलना',
    calculationTransparency: 'पारदर्शी गणना विवरण',
    attachInspectionBtn: 'जांच व मूल्य को फसल लॉट से जोड़ें',
    backToMyCrops: 'माई क्रॉप्स पर वापस जाएं',
    qualityGrade: 'गुणवत्ता ग्रेड',
    targetFocus: 'टारगेट फोकस',
    opticalSensorActive: 'ऑप्टिकल सेंसर सक्रिय',
    liveCameraInactive: 'लाइव कैमरा निष्क्रिय',
    launchCameraSensor: 'कैमरा सेंसर शुरू करें',
    noAssessmentRunYet: 'अभी तक कोई जांच नहीं की गई',
    noAssessmentRunDesc: 'अपने कैमरे को फसल के सामने रखें या फोटो अपलोड करें। एआई इंजन गुणवत्ता जांच कर वास्तविक मंडी भाव बताएगा।',
    processingScanner: 'गुणवत्ता स्कैनर और मूल्य निर्धारण इंजन चल रहा है...',
    howWasPriceCalculated: 'यह भाव कैसे तय हुआ? (पारदर्शी ऑडिट)',
    currentBatchGrade: 'वर्तमान बैच ग्रेड',
    disclaimer: 'अस्वीकरण',
    inspectionAttachedSuccess: 'गुणवत्ता निरीक्षण प्रमाणपत्र डेटाबेस में फसल लॉट से सफलतापूर्वक जोड़ दिया गया!',
    viewInMyCrops: 'माई क्रॉप्स में देखें',
    manageListings: 'लिस्टिंग प्रबंधित करें',

    // Negotiation & Offers
    offersTitle: 'खरीदार ऑफर एवं उचित मूल्य बातचीत',
    offersSubtitle: 'मंडी बेंचमार्क पर आधारित खरीदारों के साथ सीधी पारदर्शी बातचीत।',
    receivedOffers: 'प्राप्त ऑफर',
    sentOffers: 'भेजे गए ऑफर',
    offeredPrice: 'प्रस्तावित दर',
    fairFloorPrice: 'न्यूनतम उचित भाव',
    counterOfferBtn: 'काउंटर ऑफर भेजें',
    acceptOfferBtn: 'सौदा स्वीकार करें',
    rejectOfferBtn: 'ऑफर अस्वीकार करें',
    predatoryAlertTitle: 'अनुचित निम्न मूल्य चेतावनी',
    predatoryAlertDesc: 'यह ऑफर न्यूनतम उचित बाजार भाव से बहुत कम है। कृपया काउंटर ऑफर भेजें।',

    // Orders & Logistics
    ordersTitle: 'ऑर्डर और अनुबंध प्रबंधन',
    ordersSubtitle: 'सुरक्षित एस्क्रो गारंटी के साथ चरणबद्ध बिक्री अनुबंध।',
    orderCode: 'ऑर्डर कोड',
    escrowStatus: 'एस्क्रो स्थिति',
    logisticsTrackingTitle: 'लाइव माल ढुलाई एवं परिवहन ट्रैकिंग',
    transitStage: 'परिवहन चरण',
    driverContact: 'चालक का फोन',
    vehicleNumber: 'गाड़ी नंबर',

    // Buyer Matching & Direct Commerce
    buyerMatchingTitle: 'एआई खरीदार मिलान इंजन',
    buyerMatchingSub: '६-कारकीय भारित एल्गोरिदम: मूल्य, दूरी, गुणवत्ता ग्रेड, मांग की तात्कालिकता और एस्क्रो विश्वसनीयता।',
    filterByCrop: 'फसल अनुसार चुनें',
    filterByLocation: 'स्थान / जिला अनुसार चुनें',
    allCrops: 'सभी फसलें',
    allLocations: 'सभी स्थान',
    budgetRate: 'बजट दर',
    targetVolume: 'मांग मात्रा',
    deliveryDate: 'आवश्यकता तिथि',
    sendOfferBtn: 'ऑफर भेजें',
    sendOfferModalTitle: 'सीधा व्यापार प्रस्ताव भेजें',
    sendOfferModalDesc: 'अपनी प्रस्तावित दर और मात्रा दर्ज करें। उचित मूल्य इंजन आपको सर्वोत्तम सौदा तय करने में सहायता करेगा।',
    buyerTargetBudget: 'खरीदार का बजट',
    fairPriceCorridor: 'उचित भाव पट्टा',
    escrowSecurity: 'एस्क्रो सुरक्षा',
    guaranteed100: '१००% सुरक्षित गारंटी',
    yourPricePerKg: 'आपकी दर (₹/किलो)',
    quantityKgLabel: 'मात्रा (किलो)',
    dispatchNotes: 'प्रेषण एवं गुणवत्ता विवरण',
    sendFormalOffer: 'सीधा प्रस्ताव भेजें',
    viewDetails: 'विवरण देखें',
    netRealizationEngine: 'निव्वळ प्रत्यक्ष दर इंजन',
    bestMarketHeading: 'सर्वश्रेष्ठ मंडी एवं बाजार अनुशंसा',
    bestMarketSub: 'परिवहन लागत, लोडिंग और मंडी शुल्क घटाने के बाद शुद्ध लाभ की तुलना करें।',
    originDistrict: 'मूल खेत जिला',
    selectCrop: 'फसल चुनें',
    harvestQuantityKg: 'फसल मात्रा (किलो)',
    calculateNetRealization: 'शुद्ध दर की गणना करें',
    recommendedMandi: 'सर्वश्रेष्ठ अनुशंसित मंडी',
    alternativeMarkets: 'वैकल्पिक एपीएमसी मंडियां',
    proximityNet: 'निकटता शुद्ध दर',
    aiFairPriceVerified: 'एआई उचित मूल्य प्रमाणित',
    docaEscrowProtected: 'उपभोक्ता कार्य विभाग (DoCA) एस्क्रो सुरक्षित',
    truckFillRate: 'ट्रक भराव दर',
    standardFreight: 'मानक मालभाड़ा',
    savedAmount: 'बचत',
    distance: 'दूरी',
    escrowSecured: '१००% एस्क्रो सुरक्षित',
    verifiedCorporateBuyer: 'सत्यापित प्रत्यक्ष कॉर्पोरेट खरीदार',
    calculatedAfterFreight: 'मालभाड़ा कटौती के उपरांत',
    netRealizationSubtitle: 'शुद्ध प्रत्यक्ष खेत-गेट प्राप्ति',
    activeOrderSubtitle: 'खरीदार हब के मार्ग पर',
    viewNegotiations: 'सक्रिय बातचीत देखें',
    noBuyersFound: 'इस फसल और स्थान के लिए कोई खुली खरीदार आवश्यकता उपलब्ध नहीं है।',
  },

  mr: {
    // Navigation & App Shell
    dashboard: 'डॅशबोर्ड',
    aiAdvisor: 'एआय सल्लागार (सारथी)',
    myCrops: 'माझी पिके',
    marketIntel: 'बाजार भाव व अंदाज',
    findBestMarket: 'सर्वोत्तम बाजारपेठ शोधा',
    findBuyers: 'नोंदणीकृत खरेदीदार',
    offersNegotiations: 'ऑफर व वाटाघाटी',
    cropPlanning: 'स्मार्ट पीक शिफारस',
    qualityAssessment: 'एआय दर्जा तपासणी',
    orders: 'सक्रिय ऑर्डर',
    logistics: 'थेट वाहतूक (लॉजिस्टिक्स)',
    earnings: 'उत्पन्न व नफा विश्लेषण',
    cropPassport: 'डिजिटल पीक पासपोर्ट',
    fairPriceEngine: 'वाजवी भाव इंजिन',
    searchPlaceholder: 'पिके, बाजारपेठा, खरेदीदार शोधा...',
    signOut: 'साइन आउट करा',
    editProfile: 'माहिती संपादित करा',
    saveChanges: 'बदल जतन करा',
    cancel: 'रद्द करा',
    notifications: 'सूचना (नोटिफिकेशन्स)',
    allCaughtUp: 'कोणतीही नवीन सूचना नाही!',

    // Dashboard Greetings & Cards
    goodMorning: 'शुभ सकाळ',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    docaTagline: 'भारत सरकार — ग्राहक व्यवहार विभाग (DoCA)',
    heroSub: 'एआय गुणवत्ता श्रेणी आणि वाजवी भाव संरक्षणासह शेतकरी, खरेदीदार आणि FPO यांना जोडणारे थेट कृषी-वाणिज्य इंजिन।',
    farmHolding: 'शेतीचे क्षेत्र',
    acres: 'एकर',
    inLocation: 'येथे',
    trustScore: 'विश्वासार्हता गुण',
    produceQualityScanner: 'शेतमाल दर्जा स्कॅनर',
    scanProduceDesc: 'थेट एपीएमसी बाजारभावासह कॅमेऱ्याद्वारे तात्काळ अचूक दर्जा मूल्यांकन.',
    scanProduceBtn: 'स्कॅन करा',
    cropRecommendationTitle: 'स्मार्ट पीक शिफारस',
    cropRecommendationDesc: 'जमीन, हवामान आणि नफा अंदाजानुसार शास्त्रीय पीक निवड.',
    planCropsBtn: 'पीक नियोजन',
    findBuyersTitle: 'नोंदणीकृत खरेदीदार',
    findBuyersDesc: 'दलालांशिवाय थेट गिरणी मालक व घाऊक खरेदीदारांशी जोडा.',
    viewBuyersBtn: 'खरेदीदार पहा',
    fairPriceNegotiation: 'वाजवी भाव वाटाघाटी',
    fairPriceNegotiationDesc: 'कमी भावात होणाऱ्या फसवणुकीपासून एआयचे थेट संरक्षण.',
    viewOffersBtn: 'ऑफर पहा',
    registeredCropsTitle: 'माझी नोंदणीकृत पिके (शेतमाल लॉट)',
    registeredCropsSub: 'कापणीनंतर थेट विक्रीसाठी तयार असलेले प्रमाणित शेतमाल लॉट.',
    addNewBatch: 'नवीन पीक लॉट जोडा',
    viewPassport: 'डिजिटल पासपोर्ट',
    activeOrdersCard: 'सक्रिय थेट ऑर्डर',
    totalEarningsCard: 'एकूण प्रमाणित उत्पन्न',
    offersReceivedCard: 'प्राप्त खरेदी ऑफर',
    liveMandiSpotPrices: 'थेट एपीएमसी बाजार भाव',
    modalPriceLabel: 'सरासरी बाजार भाव (मॉडेल रेट)',
    change24h: '२४ तासांतील कल',
    viewMandiDetails: 'बाजार विश्लेषण पहा',

    // Decision Engine Cockpit
    decisionEngineHeader: 'एक-स्क्रीन निर्णय इंजिन कॉकपिट',
    decisionEngineSub: 'तुमचा शेतमाल, एआय भाव अंदाज, सर्वोत्तम जवळची बाजारपेठ आणि थेट खरेदीदाराचे थेट संकलन.',
    harvestDetailsTitle: 'शेतमाल लॉट तपशील',
    cropLabel: 'पीक',
    quantityLabel: 'प्रमाण (वजन)',
    qualityGradeLabel: 'दर्जा प्रत',
    shelfLifeLabel: 'साठवणूक क्षमता',
    marketIntelligenceTitle: 'बाजारपेठ बुद्धिमत्ता',
    currentMandiRate: 'सध्याचा बाजार भाव',
    predictedRate3Days: '३ दिवसांनंतरचा अंदाजित भाव',
    fairPriceRangeLabel: 'वाजवी भाव पट्टा',
    aiRecommendationLabel: 'एआय शिफारस',
    bestMarketTitle: 'सर्वोत्तम अनुशंसित बाजारपेठ',
    grossMarketPrice: 'एकूण बाजार भाव',
    transportFreight: 'वाहतूक / मालभाडे खर्च',
    platformTechFee: 'प्लॅटफॉर्म शुल्क',
    netRealizationRate: 'निव्वळ प्रत्यक्ष दर',
    estimatedBatchNet: 'एकूण निव्वळ उत्पन्न (लॉट मूल्य)',
    bestMatchedBuyerTitle: 'सर्वात योग्य जुळणारा खरेदीदार',
    buyerNameLabel: 'खरेदीदार आस्थापना',
    matchScoreLabel: 'मॅच स्कोअर',
    buyerOfferRate: 'प्रस्तावित दर',
    requiredDelivery: 'डिलिव्हरी वेळ',
    acceptBuyerOfferBtn: 'ऑफर स्वीकारा व व्यवहार सुरू करा',
    smartLogisticsTitle: 'स्मार्ट थेट वाहतूक',
    logisticsSavings: 'एकत्रित मालवाहतुकीत बचत',
    pooledTruckRoute: 'थेट शेत-ते-खरेदीदार वाहतूक मार्ग',

    // Crop Planning
    cropRecTitle: 'स्मार्ट पीक शिफारस आणि जमीन उपयुक्तता इंजिन',
    cropRecSubtitle: 'आपल्या शेतासाठी ICAR आणि OWID शास्त्रीय डेटावर आधारित अचूक पीक निवड आणि नफा अंदाज.',
    analyzeMyLand: 'माझ्या जमिनीचे विश्लेषण करा',
    analyzingLand: 'माती, हवामान आणि बाजाराचे विश्लेषण सुरू आहे...',
    topRecommendedCrops: 'आपल्या शेतासाठी सर्वाधिक योग्य ३ पिके',
    overallSuitabilityScore: 'एकूण उपयुक्तता गुण',
    whyThisCrop: 'आपल्या जमिनीसाठी हेच पीक का?',
    financialEstimates: 'आर्थिक अंदाज (आपल्या शेताच्या क्षेत्रफळानुसार)',
    cultivationCost: 'अंदाजे लागवड खर्च',
    projectedGrossRevenue: 'अपेक्षित एकूण उत्पन्न',
    projectedNetProfit: 'अपेक्षित निव्वळ नफा',
    yieldBenchmarking: 'उत्पादकता तौलनिक अभ्यास (OWID व ICAR)',
    districtAverage: 'जिल्ह्याचे ऐतिहासिक उत्पादन',
    stateAverage: 'राज्याची सरासरी',
    nationalBenchmark: 'राष्ट्रीय प्रगतीशील मानक',
    yieldGap: 'उत्पादकता फरक (Yield Gap)',
    askSaarthi: 'सारथी AI ला या पिकाबद्दल विचारा',
    nearbyAgriCenters: 'जवळचे कृषी विज्ञान केंद्र (KVK) व माती परीक्षण प्रयोगशाळा',
    planThisCrop: 'हे पीक निवडा व नियोजन करा',
    activePlansTitle: 'माझी सक्रिय पीक लागवड नियोजन यादी',

    // Quality Assessment
    qualityAssessmentTitle: 'शेतमाल दर्जा स्कॅनर आणि थेट बाजारभाव मूल्य निर्धारण',
    qualityAssessmentSubtitle: 'थेट एपीएमसी बाजार आवक, हमीभाव (MSP) आणि दर्जा नियमांवर आधारित थेट संगणकीय दृष्टी (Computer Vision) प्रतवारी.',
    cameraAndProduceInput: 'कॅमेरा व शेतमाल इनपुट',
    liveSensor: 'थेट सेन्सर',
    uploadPhotosTab: 'फोटो अपलोड करा',
    selectRegisteredCropBatch: 'नोंदणीकृत शेतमाल लॉट निवडा',
    produceCommodity: 'शेतमाल / पीक',
    batchQuantityKg: 'लॉट प्रमाण (किलो)',
    runAiQualityEngine: 'एआय गुणवत्ता व बाजार मूल्य तपासणी सुरू करा',
    clickToUploadPhoto: 'शेतमालाचा फोटो अपलोड करण्यासाठी क्लिक करा',
    multiPhotoInspectionTray: 'बहु-फोटो तपासणी ट्रे',
    opticalScore: 'ऑप्टिकल स्कोअर',
    ripenessIndex: 'परिपक्वता निर्देशांक',
    visibleDefects: 'दृश्यमान दोष / नुकसान',
    threeStateVerification: '३-स्तरीय ऑप्टिकल पडताळणी',
    detected: 'आढळले',
    notDetected: 'आढळले नाही',
    notAssessable: 'तपासणी अशक्य',
    estimatedQualityPrice: 'अपेक्षित दर्जा भाव',
    totalBatchValue: 'एकूण लॉट मूल्य',
    mandiModalBaseline: 'बाजार समिती मोडल आधार भाव',
    premiumOverModal: 'मोडल दरापेक्षा प्रीमियम (नफा)',
    discountUnderModal: 'दर्जा घसारा (कपात)',
    changePhoto: 'फोटो बदला',
    clearAll: 'सर्व काढा',
    capturePhotosTitle: 'टप्पा १: बहु-फोटो ऑप्टिकल कॅप्चर',
    startLiveCamera: 'थेट कॅमेरा सुरू करा',
    stopLiveCamera: 'कॅमेरा बंद करा',
    takeSnapshot: 'फोटो काढा',
    orUploadImages: 'किंवा उच्च दर्जाचे फोटो अपलोड करा',
    imageQualityPreCheck: 'फोटो दर्जा पूर्व-तपासणी',
    structuredObservationsTitle: 'रचनात्मक दृश्य निरीक्षण (३-स्तरीय मॉडेल)',
    estimatedMarketValueTitle: 'अपेक्षित प्रत्यक्ष बाजार मूल्य',
    expectedMandiRange: 'अपेक्षित बाजारभाव पट्टा',
    batchValueRealization: 'एकूण लॉट मूल्य प्राप्ती',
    potentialFarmerGain: 'सरासरी बाजारभावापेक्षा शेतकऱ्याला अतिरिक्त नफा',
    priceComparisonByGrade: 'दर्जा प्रतीनुसार बाजारभाव तुलना',
    calculationTransparency: 'पारदर्शक आर्थिक हिशेब तपशील',
    attachInspectionBtn: 'तपासणी व भाव शेतमाल लॉटशी जोडा',
    backToMyCrops: 'माझी पिके कडे परत जा',
    qualityGrade: 'गुणवत्ता प्रत (ग्रेड)',
    targetFocus: 'टार्गेट फोकस',
    opticalSensorActive: 'ऑप्टिकल सेन्सर सक्रिय',
    liveCameraInactive: 'थेट कॅमेरा बंद आहे',
    launchCameraSensor: 'कॅमेरा सेन्सर सुरू करा',
    noAssessmentRunYet: 'अद्याप तपासणी झालेली नाही',
    noAssessmentRunDesc: 'आपल्या कॅमेऱ्यासमोर शेतमाल धरा किंवा फोटो अपलोड करा. एआय इंजिन दर्जा तपासून थेट बाजारभाव निश्चित करेल.',
    processingScanner: 'गुणवत्ता स्कॅनर आणि मूल्य निर्धारण प्रक्रिया सुरू आहे...',
    howWasPriceCalculated: 'हा भाव कसा निश्चित झाला? (पारदर्शक हिशेब)',
    currentBatchGrade: 'सध्याचा लॉट दर्जा',
    disclaimer: 'सूचना / अस्वीकरण',
    inspectionAttachedSuccess: 'गुणवत्ता तपासणी प्रमाणपत्र डेटाबेसमध्ये शेतमाल लॉटशी यशस्वीरित्या जोडले गेले!',
    viewInMyCrops: 'माझ्या पिकांमध्ये पहा',
    manageListings: 'विक्री यादी व्यवस्थापित करा',

    // Negotiation & Offers
    offersTitle: 'खरेदीदार ऑफर आणि वाजवी भाव वाटाघाटी',
    offersSubtitle: 'घाऊक बाजारभावाच्या आधारावर खरेदीदारांशी थेट पारदर्शक वाटाघाटी.',
    receivedOffers: 'प्राप्त झालेल्या ऑफर',
    sentOffers: 'पाठवलेल्या ऑफर',
    offeredPrice: 'प्रस्तावित दर',
    fairFloorPrice: 'किमान वाजवी भाव',
    counterOfferBtn: 'प्रति-प्रस्ताव (काउंटर) पाठवा',
    acceptOfferBtn: 'सौदा स्वीकारा',
    rejectOfferBtn: 'ऑफर नाकारा',
    predatoryAlertTitle: 'कमी दराबाबत धोक्याचा इशारा',
    predatoryAlertDesc: 'ही ऑफर किमान वाजवी दरापेक्षा खूप कमी आहे. आम्ही काउंटर ऑफर पाठवण्याची शिफारस करतो.',

    // Orders & Logistics
    ordersTitle: 'ऑर्डर आणि खरेदी करार व्यवस्थापन',
    ordersSubtitle: 'सुरक्षित एस्क्रो हमीसह टप्प्याटप्प्याने पूर्ण होणारे शेतमाल करार.',
    orderCode: 'ऑर्डर कोड',
    escrowStatus: 'एस्क्रो सुरक्षित रक्कम',
    logisticsTrackingTitle: 'थेट मालवाहतूक व वाहन ट्रॅकिंग',
    transitStage: 'वाहतुकीचा टप्पा',
    driverContact: 'चालकाचा फोन',
    vehicleNumber: 'वाहन क्रमांक',

    // Buyer Matching & Direct Commerce
    buyerMatchingTitle: 'एआय थेट खरेदीदार शोध व जुळवणी इंजिन',
    buyerMatchingSub: '६-घटक भारित अल्गोरिदम: दर, अंतर, गुणवत्ता प्रत, मागणीची निकड आणि एस्क्रो विश्वासार्हता.',
    filterByCrop: 'पिकानुसार निवडा',
    filterByLocation: 'जिल्हा / बाजारपेठ निवडा',
    allCrops: 'सर्व पिके',
    allLocations: 'सर्व जिल्हे',
    budgetRate: 'खरेदीदार बजेट दर',
    targetVolume: 'आवश्यक प्रमाण',
    deliveryDate: 'डिलिव्हरी अंतिम मुदत',
    sendOfferBtn: 'ऑफर पाठवा',
    sendOfferModalTitle: 'थेट शेतमाल विक्री प्रस्ताव पाठवा',
    sendOfferModalDesc: 'आपला अपेक्षित दर आणि वजन प्रविष्ट करा. वाजवी भाव इंजिन सर्वोत्तम नफा मिळवून देण्यासाठी मदत करेल.',
    buyerTargetBudget: 'खरेदीदार बजेट दर',
    fairPriceCorridor: 'वाजवी भाव पट्टा',
    escrowSecurity: 'एस्क्रो सुरक्षितता',
    guaranteed100: '१००% हमी',
    yourPricePerKg: 'तुमचा दर (₹/किलो)',
    quantityKgLabel: 'वजन (किलो)',
    dispatchNotes: 'वाहतूक व शेतमाल दर्जा नोंद',
    sendFormalOffer: 'अधिकृत विक्री प्रस्ताव पाठवा',
    viewDetails: 'तपशील पहा',
    netRealizationEngine: 'निव्वळ प्रत्यक्ष दर इंजिन',
    bestMarketHeading: 'सर्वोत्तम बाजारपेठ व बाजार समिती शिफारस',
    bestMarketSub: 'वाहतूक खर्च, लोडिंग व बाजार उपकर वजा जाता प्रत्यक्ष हातात पडणाऱ्या निव्वळ भावाची थेट तुलना.',
    originDistrict: 'शेत असलेला जिल्हा',
    selectCrop: 'पीक निवडा',
    harvestQuantityKg: 'शेतमाल प्रमाण (किलो)',
    calculateNetRealization: 'निव्वळ भावाची गणना करा',
    recommendedMandi: 'सर्वोत्कृष्ट अनुशंसित बाजार समिती',
    alternativeMarkets: 'पर्यायी बाजार समित्या',
    proximityNet: 'जवळचा निव्वळ दर',
    aiFairPriceVerified: 'एआय वाजवी भाव प्रमाणित',
    docaEscrowProtected: 'ग्राहक व्यवहार मंत्रालय (DoCA) एस्क्रो सुरक्षित',
    truckFillRate: 'ट्रक भराव प्रमाण',
    standardFreight: 'सर्वसाधारण मालभाडे',
    savedAmount: 'बचत',
    distance: 'अंतर',
    escrowSecured: '१००% एस्क्रो सुरक्षित',
    verifiedCorporateBuyer: 'प्रमाणित थेट कॉर्पोरेट खरेदीदार',
    calculatedAfterFreight: 'वाहतूक खर्च वजा जाता',
    netRealizationSubtitle: 'शेतकऱ्याला मिळणारा प्रत्यक्ष निव्वळ दर',
    activeOrderSubtitle: 'खरेदीदार केंद्राकडे वाहतुकीत',
    viewNegotiations: 'सक्रिय वाटाघाटी पहा',
    noBuyersFound: 'या पिकासाठी आणि क्षेत्रासाठी सध्या कोणतीही थेट खरेदी मागणी उपलब्ध नाही.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('farm2market_language');
    if (saved === 'mr' || saved === 'hi' || saved === 'en') {
      return saved;
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('farm2market_language', lang);
  };

  const languageLabel =
    language === 'mr' ? 'मराठी' : language === 'hi' ? 'हिन्दी' : 'English';

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    if (translations.en[key]) {
      return translations.en[key];
    }
    return fallback || key;
  };

  const tcrop = (cropName: string): string => {
    if (!cropName) return '';
    const clean = cropName.trim();
    if (CROP_TRANSLATIONS[clean]?.[language]) {
      return CROP_TRANSLATIONS[clean][language];
    }
    return clean;
  };

  const tcity = (cityName: string): string => {
    if (!cityName) return '';
    const clean = cityName.trim();
    for (const [k, v] of Object.entries(CITY_TRANSLATIONS)) {
      if (clean.toLowerCase().includes(k.toLowerCase())) {
        return v[language];
      }
    }
    return clean;
  };

  const tgrade = (grade: string): string => {
    if (!grade) return '';
    const clean = grade.trim();
    if (GRADE_TRANSLATIONS[clean]?.[language]) {
      return GRADE_TRANSLATIONS[clean][language];
    }
    return clean;
  };

  const tstatus = (status: string): string => {
    if (!status) return '';
    const clean = status.trim();
    if (STATUS_TRANSLATIONS[clean]?.[language]) {
      return STATUS_TRANSLATIONS[clean][language];
    }
    return clean;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languageLabel, t, tcrop, tcity, tgrade, tstatus }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
